version: '3.7'
services:
  postgres_service:
    image: mysql:8.0.17
    ports:
      - '3306:3306'
    volumes:
      - ./schema:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=app
      - MYSQL_DATABASE=app
      - MYSQL_PASSWORD=pass